### PR TITLE
chore: bump msgraph to v1.45.0

### LINKED ISSUE #1369: azwi: failed to add federated credential, parsing time
**Describe the bug**

```
Error: failed to run phase federated-identity: failed to add federated credential: parsing time "2024-06-05T23:31:38" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```

**Steps To Reproduce**

```
azwi serviceaccount create phase federated-identity --subscription-id ID --aad-application-name backstage --service-account-namespace name --service-account-name name --service-account-issuer-url https://francecentral.oic.prod-aks.azure.com/ID/ID/ --debug
```

**Expected behavior**

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: aks
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

### PR DESCRIPTION
**Pull request by guilhem**
fix #1369

**Reason for Change**:

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [ ] no

**Notes for Reviewers**:

### CODE REVIEW

**Comment by aramase** [comment]
@guilhem could you rebase to resolve conflicts?

**Comment by guilhem** [comment]
Done @aramase

**Review by aramase — APPROVED** [review]

**Pull request merged**
