### PR TITLE
chore: Remove `creationTimestamp: null` from config

### PR DESCRIPTION
**Pull request by karataliu**
**Reason for Change**:
Simplify deployment

**Requirements**

- [ ] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [ ] no

**Notes for Reviewers**:

### CODE REVIEW

**Review by aramase — CHANGES_REQUESTED** [review]
Changes to `charts` and `deploy` dir is only done at the time of release. Could you revert that change from the files in those 2 dirs?

**Comment by karataliu** [comment]
updated.

**Review by aramase — CHANGES_REQUESTED** [review]
@karataliu The `creationTimestamp` is added automatically when generating the manifests based on `kubebuilder` markers. I don't think we can remove this manually as it'll get added back when we run `make manifests` as part of every release. Is there a reason this needs to be removed? If not, I think we can leave it as is. LMK!

**Comment by sozercan** [comment]
I beieve this needs to be addressed to remove these https://github.com/kubernetes-sigs/controller-tools/issues/402

**Comment by karataliu** [comment]
@aramase 

I'd like to keep manifest as precise as possible (for easy sync), so it's good to keep out those unnecessary lines.

It's ok to keep it there if it's autogenerated. Please close then.

**Pull request closed without merging**
